# Generated by Django 5.2.8 on 2025-11-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('IN_PROGRESS', 'In Progress'), ('done', 'Done'), ('BLOCKED', 'Blocked')], default='TODO', max_length=20),
        ),
    ]
