# Generated by Django 5.2.8 on 2025-11-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0005_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee',
            new_name='assigned_to',
        ),
    ]
