# Generated by Django 5.2.8 on 2025-11-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0006_rename_assignee_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('in-progress', 'In Progress'), ('done', 'Done'), ('review', 'Review')], default='TODO', max_length=20),
        ),
    ]
