# Generated by Django 5.2.8 on 2025-11-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'Todo'), ('in-progress', 'In Progress'), ('done', 'Done'), ('review', 'Review')], default='to-do', max_length=20),
        ),
    ]
