# Generated by Django 5.2.8 on 2025-11-13 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0004_alter_board_tickets'),
        ('tasks_app', '0009_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_of_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards_app.board'),
        ),
    ]
