# Generated by Django 5.2.8 on 2025-11-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0010_task_is_of_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_of_board',
            new_name='board',
        ),
    ]
