# Generated by Django 5.2.8 on 2025-11-13 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0011_rename_is_of_board_task_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reviewer_id',
            field=models.ManyToManyField(blank=True, related_name='reviewing_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
