# Generated by Django 5.2.8 on 2025-11-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0012_task_reviewer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assignee_id',
        ),
    ]
