# Generated by Django 5.2.8 on 2025-11-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0013_rename_assigned_to_task_assignee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
