# Generated by Django 5.2.8 on 2025-11-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0016_taskcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
