# Generated by Django 5.2.8 on 2025-11-15 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0004_alter_board_tickets'),
        ('tasks_app', '0017_rename_creator_id_task_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(blank=True, default=9, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards_app.board'),
        ),
    ]
