# Generated by Django 5.2.8 on 2025-11-15 12:46

import tasks_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0018_alter_task_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=tasks_app.models.Task.one_week_from_now),
        ),
    ]
