# Generated by Django 5.2.8 on 2025-11-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0020_alter_task_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee_id',
            new_name='assignee',
        ),
    ]
