# Generated by Django 5.2.8 on 2025-11-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('boards_app', '0002_alter_board_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='member_of_boards',
            field=models.ManyToManyField(blank=True, related_name='memberships', to='boards_app.board'),
        ),
    ]
