# Generated by Django 5.2.8 on 2025-11-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_member_of_boards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='member_of_boards',
        ),
    ]
