# Generated by Django 5.2.8 on 2025-11-12 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ticket_count', models.IntegerField(default=0)),
                ('members', models.ManyToManyField(blank=True, related_name='boards', to=settings.AUTH_USER_MODEL)),
                ('owner_id', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
