# Generated by Django 5.2.8 on 2025-11-12 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0002_alter_board_owner_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='ticket_count',
            new_name='tickets',
        ),
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
