# Generated by Django 5.2.8 on 2025-11-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0003_rename_ticket_count_board_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tickets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
