# Generated by Django 5.2.8 on 2025-11-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0004_alter_board_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
